### ISSUE TITLE
Add Request support

### ISSUE THREAD

**Issue by enix** [MassTransit/Automatonymous#1]
Hi,

I opened this issue to discuss a notation for adding Request support to the lib. The basic stuff shouldn't be hard to do, it can probably follow the Publish annotation. What might be a bit interesting modeling the timeout. 

It could be something like, following MT:

       class StateMachine 
       {
              ctor(){   
                   During(Initial,
                        When(Initialized)
                             .Request(new MyRequest(), c => {
                                   c.HandleTimeout(() => ...);
                             }
                     ));
                }
       }

or a bit more statemachine-ish approach and perhaps: 

       class StateMachine 
       {
             enum Timeouts {
                  First,
                  Second 
            }

              ctor(){   
                   During(Initial,
                        When(Initialized)
                             .Request(new MyRequest(), c => {
                                   c.SetTimeoutTag( Timeouts.First );
                             }
                     )
                    When(Timeout, Timeouts.First)
                        .Then(...);
                }
       }

Any thoughts on this? 

cheers,
Ernst

**Comment by phatboyg** [comment]
I'm going to revisit this idea soon, as part of MT3. The new request support in MT3 is TPL based, but doesn't make sense if the state machine is persisted. However, using a few states (and substates) should make it work nicely.


	interface RequestSettings<TRequest>
	{
		Uri ServiceAddress {get;}
		TimeSpan RequestTimeout {get;}
	}


	class MyStateMachine :
		AutomatonymousStateMachine<MyState>
	{

		public MyStateMachine(MyStateMachineSettings settings)
		{
			_settings = settings;

			Event(() => Asked);

			Request<TRequest, TResponse>(() => ServiceRequest, _settings);

			Initially(
				When(Asked)
					.Request(ServiceRequest, new RequestMessage(...)));

			During(ServiceRequest.Pending,
				When(ServiceRequest.Completed)
					.Then((BehaviorContext<MyState, TResponse> context) => { yeah! }),
				When(ServiceRequest.Faulted)
					.Then((BehaviorContext<MyState, Fault<TRequest>> context) => { ouch! }),
				When(ServiceRequest.TimeoutExpired)
					.Then((BehaviorContext<MyState> context) => { well, hmmm }));
		}
	}

A new method is added to define a ```Request```, which creates the appropriate events and states related to the request and response. Then they can easily be used in the state machine to orchestrate the response, timeout, or fault.

**Comment by phatboyg** [comment]
Okay, so this is totally working in the v3 branch and is super slick to use (IMHO).
