### ISSUE TITLE
Edges in visualizer shared between states. 

### ISSUE THREAD

**Issue by allensanborn** [MassTransit/Automatonymous#14]
I'm working on creating a state machine with Automatonymous and I'm running into an issues with the visualizer. I'd like to run the graph by the client but the graph doesn't really make any sense since the Events/transitions are being shared between states in the graph. 

For example, State 1 and state 2 transition to state 3 but they both use the same event which then appears as its own node on the graph. Not to0 big of an issue with 3 states and 1 transition since it only results in 4 vertexes and 3 edges but I have ~30 states and 8 events and the graph then has 130 edges in the edge collection and turns it into a soup of lines that aren't very useful since you can't tell the state->event->state relationships. I'd like to conceptually make each transition appear to be unique in the graph. This would essentially just make the event a 'label' and not a full blown state with no outline in the graph.

I'm looking at modifying the graphing code to make the edges unique but I just wanted to make sure that I'm not totally off-base in regards to this being a problem. It seems like the graphing would break down on any moderately large state machine and that I may not have been the first person to run into this.

Any suggestions?
![state](https://cloud.githubusercontent.com/assets/134248/3250779/ddd60584-f1a9-11e3-9630-d175c2020916.png)

**Comment by phatboyg** [comment]
I just fixed this in the mt3 branch, which is going to released as yet another prerelease version shortly (3.0.2)
