### ISSUE TITLE
Documentation Needs Improving

### ISSUE THREAD

**Issue by madhon** [MassTransit/Automatonymous#15]
The documentation needs improving a lot, samples etc

**Comment by finottis** [comment]
+1

**Comment by phatboyg** [comment]
Yeah, I suck, I need to write more comprehensive documentation for one of the best capabilities used by MassTransit.

This actually gives a lot of help: http://docs.masstransit-project.com/en/latest/usage/sagas/automatonymous.html

**Comment by igor-toporet** [comment]
Above link is broken. Here's up to date one I believe http://masstransit-project.com/MassTransit/advanced/sagas/automatonymous.html

**Comment by phatboyg** [comment]
The latest: https://masstransit-project.com/usage/sagas/automatonymous.html#composite-event

Also, closing, as I'm considering this documented.
