### ISSUE TITLE
RetryLater MassTransit extension interacts poorly with Try

### ISSUE THREAD

**Issue by chrisblock** [MassTransit/Automatonymous#17]
When using `Try` in combination with `RetryLater`, the `ContextStorage` class attempts to pull the `IConsumeContext` for a `Tuple<Message, Exception>`, which throws an invalid operation exception.

**Comment by phatboyg** [comment]
This has been completely rewritten for the v3 release, so it's been addressed in what I think is a much nicer syntax.
