### ISSUE TITLE
Dynamic states

### ISSUE THREAD

**Issue by ronnyek** [MassTransit/Automatonymous#20]
I completely understand the examples in the Wiki, but was curious if there was a way to have user configurable state machines (eg, user defines 5 states and the rules, and I can build how that stuff gets created/loaded if necessary) and have Automatonymous handle the transitions and the rules etc?

**Comment by phatboyg** [comment]
It's not something I've considered as part of the design, honestly.

**Comment by MasallahOZEN** [comment]
Hi, are there any solution for dynamic states?

**Comment by phatboyg** [comment]
No.
