### ISSUE TITLE
Unable to determine if transition is allowed

### ISSUE THREAD

**Issue by StuartBaker65** [MassTransit/Automatonymous#21]
StateMachine.NextEvents() tells me what events I can issue to attempt a transition.  Is there a way the machine is able to tell me if an event is _actually_ permissable without executing the transition?

The introspection test The_next_events_should_be_known shows that the machine is able to enumerate the event correctly, but this test has no guard conditions in the state machine.

If one of the transitions was amended to support:

``` c#
During(Greeted,
        When(Handshake, (c => c.Instance.Data.Grip = GripType.Perfect)
                .TransitionTo(Loved),
        When(Handshake, (c => c.Instance.Data.Grip = (GripType.TooHard || GripType.TooLimp)
                .TransitionTo(Pissed),
```

Given that calls are required to pass the object containing state - how would you obtain the result that there are only 2 were valid events given the guard constraints now placed on Greeted and constrained with "GripType.Perfect" .... the transition to "Pissed" is not viable?

**Comment by phatboyg** [comment]
Clever example, laughing!

This could be an additional method, where you could pass the event to see if it would be accepted by the state machine (including the When() clause evaluation).

**Comment by phatboyg** [comment]
This is actually pretty difficult given the way activity filters are implemented right now. Essentially, each activity that is part of a state/event behavior may have a filter condition. There is presently no way to evaluate the activities to see if the event _would_ execute the activity.

It's a sensible idea, but I feel the effort to rework this right now is more than I want to take on considering the level of testing. I'll likely get to it eventually, just not in the next couple of weeks.

**Comment by phatboyg** [comment]
It's been over two years, I'm unlikely to address this so closing it.
