### ISSUE TITLE
How to subscribe to any state change

### ISSUE THREAD

**Issue by samqty** [MassTransit/Automatonymous#26]
I would like to add an implementation in my state machine definition that would allow me to execute some code when ever the state of a saga instance changes. That is regardless of what the current state of the saga.

I see there that there are some methods that would allow you to subscribe to state changes on from or to a predetermined state. I am referring to the methods WhenEnter,WhenLeave .. on AutomatonymousStateMachine class. In order to use this I would have to explicitly tell it what state to consider. 

So my question is ,

-Is there a utility that would allow me to subscribe to any state change and allow me to execute some piece of code when ever that happens?

I hope this makes sense.

**Comment by phatboyg** [comment]
That would be a great feature request, I don't think there is an easy way to do that now.

**Comment by samqty** [comment]
Where do I submit a feature request?, if you don't mind me asking :)

**Comment by phatboyg** [comment]
Submit an issue. Or edit the issue to be the request.

**Comment by phatboyg** [comment]
I think this is addressed by the work on #27 

There is also the observer-based work around the state machine, but that's not meant to be behavior within the state machine itself but an audit/tracing utility.
