### ISSUE TITLE
Extend During with more states

### ISSUE THREAD

**Issue by alexeyzimarev** [MassTransit/Automatonymous#29]
Currently when using `During` and some event that can happen in more than one state, we must duplicate the event handling in each state. Some events are even possible in all states and we get even more duplication, leading to extensive code changes in case the logic needs to be changed.

Wouldn't it be nicer to have `During(State[], ...)` and `DuringAny(..)`?

**Comment by phatboyg** [comment]
Well, `DuringAny` already exists...

And there are `During(state)`, `During(state,state)`, `During(state,state,state)`, `During(state,state,state,state)` and `During(IEnumerable<State>)` overloads...

Are they not showing up for you?

**Comment by alexeyzimarev** [comment]
OK, this is nice, thanks Chris :) I somehow missed these overloads.
