### ISSUE TITLE
How to use instance specific state type?

### ISSUE THREAD

**Issue by joonhwan** [MassTransit/Automatonymous#31]
In my instance's type, how do i use my custom state type instead of "string" or Automatonymous.State for 
```
public enum HumorState 
{
   Grinny,
   Smiley,
   Laughy,
   LOL
}
class RidiculousPerson
{
   public string Name { get; set; }
   public int Age { get; set; }
   public HumorState State { get; set; }
}
```

I've not figured out how to integrate this kind of type to statemachine via ```InstanceState``` method.
I'm using 3.5.0.0(?! hmm. I though I pulled Automatonymous.3.5.5-develop  but dll version displayed in VisualStudio  properties window does mismatch.)

Any hint?

**Comment by joonhwan** [comment]
Ok, maybe it is likely that I need a state mapper between ```HumorState`` to ```Automatonymous.State```.
I found access ```_accessor``` of ```StateAccessor `` that statemachine use for get/set state but how to set my own one?  
The overload ```InstanceState()``` does not allow me to set my own custom accessor.

**Comment by phatboyg** [comment]
The states have to map to Automatonymous State types, they can't be an enum or otherwise. There is built-in mapping for `string` and `int` - so you could in theory map to your enum `int` value...

**Comment by joonhwan** [comment]
I found [Test code](https://github.com/MassTransit/Automatonymous/blob/master/src/Automatonymous.Tests/State_Specs.cs#L112) that seems relavant to your comment, which unfortunately not enough for me to udnerstand.

According to comment on the overload ```InstanceState()``` method.. 

```
    /// <summary>
    /// Declares the property to hold the instance's state as an int (0 - none, 1 = initial, 2 = final, 3... the rest)
    /// </summary>
    /// <param name="instanceStateProperty"></param>
    /// <param name="states">Specifies the states, in order, to which the int values should be assigned</param>
   protected void InstanceState(Expression<Func<TInstance, int>> instanceStateProperty, params State[] states)
```

, What is ```none```, ```final`` state?
 I think I understand ```initial``` state but no idea of ```none`` state.
I think there might be multiple or no ```final``` state.
(for example, any Job that can be stopped or is re-runable. In that case Job has no final state.)

Any advice would be appreciated.

**Comment by phatboyg** [comment]
Add your states, in order, so that they're assigned to unique integers.
