### ISSUE TITLE
How to handle exceptions in an activity 

### ISSUE THREAD

**Issue by renetitulaer** [MassTransit/Automatonymous#33]
Hi,

I like Automatonymous up to know, it's only a pitty that there is not much documentation. I can't figure out how to handle exceptions in activities.

When an exception occurs I want to know this after the raise of the event.

**Comment by renetitulaer** [comment]
Looks like I found it. Don't know if this is the proper way but I have this now:
            DuringAny(
                  When(TriggerConnect)
                    .Execute(c => new ConnectActivity())                  
                    .TransitionTo(Finished)
                    .Catch<Exception>(ex => ex.Then(ctx => 
                        {
                            Console.WriteLine("Catch handled");
                            ctx.Instance.CurrentState = Failed;
                        }))                      ,
                  When(Connected)
                    .TransitionTo(ConnectionEstablished)

            );

In the error situation, currentstate will be failed: 
machine.RaiseEvent(workflow, machine.TriggerConnect);
            if (workflow.CurrentState == machine.Failed)
            {
                Console.WriteLine("error occured");
            }

**Comment by phatboyg** [comment]
Yeah, I haven't completed the documentation yet: http://masstransit-project.com/Automatonymous/

But that's a good one to add, as it's important to understand and use.

**Comment by vborza** [comment]
Hi, I really like masstransit and we are evaluating it as servicebus for our production environment. What I was missing was an example for exception handling in sagas like this - it's pity that your documentation is not complete yet - even when it's so big already - it took my a day to go through it and it's written really well :).

**Comment by hmtimany** [comment]
What if we have multiple exception types could be thrown?
