### ISSUE TITLE
Conditional processing: why I am here?

### ISSUE THREAD

**Issue by ushenkodmitry** [MassTransit/Automatonymous#34]
Hi,
I have a strong feeling that I'm not supposed to be here, but I am here!
![why_here_in_automatonymous](https://cloud.githubusercontent.com/assets/16700959/24614816/1a243a0a-1895-11e7-8c41-78d86ca99fc2.png)
Automatonymouse version 3.5.0

**Comment by phatboyg** [comment]
These unit tests cover that, and they're both passing for me.

https://github.com/MassTransit/Automatonymous/blob/master/src/Automatonymous.Tests/Condition_Specs.cs#L21

And I verified with yet another unit test, so...

**Comment by ushenkodmitry** [comment]
For some reason the If condition not evaluating. Execution doesn't stop at the breakpoint if I put it in the condition.

**Comment by ushenkodmitry** [comment]
Hm... I think I know why this happens. 
This code has a bug -- all "if" branches will be executed, no matter what condition:

    During(SomeState,
        When(SomeEvent, context => true)
            .If(context => false, binder => {})
            .If(context => false, please!!!, binder => {})

But this code works as expected -- only the truly branch will be executed:

    During(SomeState,
        When(SomeEvent)
            .If(context => false, binder => {})
            .If(context => true, binder => {})

The only difference in the second line 
    `When(SomeEvent)`

First code snippet has filtering expression that evaluates to true, so all inner conditions automatically evaluates to true too.

**Comment by ushenkodmitry** [comment]
Hi @phatboyg 
No, your unit tests don't cover this case. Check the PR.
