### ISSUE TITLE
Filtered events don't trigger OnUnhandledEvent

### ISSUE THREAD

**Issue by gp-alex** [MassTransit/Automatonymous#41]
Hey,

I've got a user input processing machine as follows:

>                 During(
>                    UserInput,
>                    When(Key1)
>                        .TransitionTo(Menu1),
>                    When(Key2, ctx => ctx.Instance.IsSpecialUser)
>                        .TransitionTo(Menu2),
>                    When(KeyBack)
>                        .Finalize()
>                );
>                OnUnhandledEvent(
>                   /* force a re-prompt */
>                )

As stated, user can input 1 or BACK, and special user can input also 2. When invalid key is pressed, user is re-prompted in error handler.
But if When(Key2, .. is used, even if condition fails event in no longer treated as unhandled and doesn't trigger an error.

Is it by design and how to undandle/discard an event then?

Thank you

**Comment by phatboyg** [comment]
Well, it's an interesting challenge. Technically, the event is handled in that state, but the event itself doesn't meet the filter requirements. I'll have to backlog this one until I have time to think about how I would signal that back out since it was technically handled, but ignored due to the event content.

**Comment by gp-alex** [comment]
There is multiple ways how that could be implemented. My actual use-case atm is as follows:

>                During(
>                    MenuWaitingForInput,
>                    When(UserInput, ctx => ctx.Instance.NumFailedAttemps > 1)
>                        .TransitionTo(Error),
>                    When(UserInput, ctx => ctx.Instance.UserInput == "1")
>                        .TransitionTo(Menu1),
>                    When(UserInput, ctx => ctx.Instance.UserInput == "2")
>                        .Then(
>                            (ctx) =>
>                            {
>                                if (!ctx.Instance.UserState.IsSpecialUser)
>                                {
>                                    ctx.Instance.NumFailedAttemps += 1;
>                                    this.TransitionToState(ctx.Instance, MenuReprompt);
>                                }
>                                else
>                                {
>                                    this.TransitionToState(ctx.Instance, Menu2);
>                                }
>                            }
>                        ),
>                    When(UserInput, ctx => ctx.Instance.UserInput == "#")
>                        .Finalize(),
>                    When(UserInput, ctx => new string[]{ "3", "4", "5", "6", "7", "8", "9" >}.Contains(ctx.Instance.UserInput))
>                        .Then(ctx => ctx.Instance.NumFailedAttemps += 1)
>                        .TransitionTo(MenuReprompt)
>                 )

I have different menus and submenus with different choices available based on Instance state.
The general idea of this issue is lacking of "default" functionality of a naive switch-case fsm
