### ISSUE TITLE
How to handle multiple requests of the same type?

### ISSUE THREAD

**Issue by MrZoidberg** [MassTransit/Automatonymous#43]
I'd like to have an ability to store multiple requests with the same signature in my MassTransitStateMachine. e.g. something like this:
```
class Workflow : MassTransitStateMachine<Work> 
{
    public List<Request<Work, ProcessRenderTask, ProcessRenderTaskFinished>> RenderRequest { get; private set; }
}
```

is it possible? or maybe some workaround to implement such behavior?

**Comment by phatboyg** [comment]
This isn't supported out of the box, it's a fan-out case, where I'd likely use a parent state machine with multiple parallel separate state machine instances.
