### ISSUE TITLE
Scheduled expirationId / tokenId usage

### ISSUE THREAD

**Issue by svechin** [MassTransit/Automatonymous#45]
Could someone explain meaning of expirationId / tokenId in scheduled event ?

`Schedule(() => CartExpired, x => x.ExpirationId ??????, x => {  .....  });`

Documentation says "This is an identifier that is used by the state machine's scheduling feature, to capture the scheduled message identifier". But it's not clear if this is property which saga needs only for internal needs or you can use it somehow to control scheduled event. 

p.s. if there is better description somewhere please point. 

Thanks.

**Comment by phatboyg** [comment]
When a message is scheduled, a TokenId is generated that identifies the scheduled message. If the message scheduler supports cancellation (which Quartz does), and the state machine later tries to Unschedule() the message (such as cancelling a future timeout message), that tokenId is used to cancel the previously scheduled message.

If it isn't saved, the message cannot be cancelled. It should be a nullable property in the saga persistence definition.

**Comment by svechin** [comment]
thanks!
