### ISSUE TITLE
MassTransit.Automatonymous.AutofacIntegration documentation

### ISSUE THREAD

**Issue by ComputerHippie** [MassTransit/Automatonymous#49]
Hi,

Can somebody provide any documentation and/or examples about MassTransit.Automatonymous.AutofacIntegration?

Most actual questions for me:
- how to use AutofacStateMachineActivityFactory?
- second question related to first and comes from code of [AutofacStateMachineActivityFactory,cs](https://github.com/MassTransit/MassTransit/blob/develop/src/Containers/MassTransit.Automatonymous.AutofacIntegration/AutofacStateMachineActivityFactory.cs): how to register ILifetimeScope in context?

Thanks

**Comment by phatboyg** [comment]
The lifetime scope should already be added by the Autofac saga repository, so it's already there. The activity factory uses that lifetime scope to resolve any state machine activities that are required.

This unit tests shows how an activity is registered, and the state machine saga added to the receive endpoint.

https://github.com/MassTransit/MassTransit/blob/master/src/Containers/MassTransit.Containers.Tests/AutofacStateMachineSaga_Specs.cs#L52

**Comment by phatboyg** [comment]
The latest Autofac (and other container) integration support, including registration, takes care of all this stuff now so I'm closing this issue.

http://masstransit-project.com/MassTransit/usage/containers/autofac.html
