### ISSUE TITLE
TypeLoadException when trying to create new MyStateMachine  : MassTransitStateMachine<MySaga> 

### ISSUE THREAD

**Issue by jerackista** [MassTransit/Automatonymous#53]
Does anyone have idea what reference is missing. I can't find anything in EventCorrelationConfigurator or AutomatonymousIntegration

System.TypeLoadException: 'Could not load type 'Automatonymous.EventCorrelationConfigurator`2' from assembly 'MassTransit.AutomatonymousIntegration, Version=5.1.5.1633, Culture=neutral, PublicKeyToken=b8e0e9f2f1e657fa'.'

**Comment by phatboyg** [comment]
How are your event types defined? Public types, such as an interface or class?

**Comment by phatboyg** [comment]
So it might be that .NET requires a package reference to resolve the type?

**Comment by jerackista** [comment]
I've had all libraries referenced in dll. No idea what's happening I guess we can close this until I'll have more information. Thank you.
