### ISSUE TITLE
Is there any option to have Fault<> consumer in MassTransitStateMachine?

### ISSUE THREAD

**Issue by lexCerveza** [MassTransit/Automatonymous#54]
I have a saga which subscribes to response events which are produced by external services. In other words, saga publishes message, external event handler subscribed and responds to saga. These external event handlers have also Fault<> consumers. So, the question is, can saga be configured subscribe to these fault consumers ?

**Comment by phatboyg** [comment]
Yes, Faults can be observed by state machines.

```
public Event<Fault<CreateCustomer>> CreateCustomerFaulted {get; private set;}
```

To initialize it:
```
Event(() => CreateCustomerFaulted, x => x.CorrelateById(m => m.Message.Message.CommandId));
```

Correlating on the original message property, which is included in the fault message.

**Comment by lexCerveza** [comment]
@phatboyg 
And how it works with saga subscribed ? 
If external event handler fails with exception n times, Fault<> handler will be triggered on this external service and saga ?

**Comment by phatboyg** [comment]
If a consumer throws an exception, and exhausts all retries, the Fault<T> is published by MT. Assuming that a saga is observing that Fault<T> event, and it can be correlated to a saga instance, either a new instance or existing instance, it would be delivered to the saga.

**Comment by lexCerveza** [comment]
@phatboyj
Thanks, you’ve helped me a lot
