### ISSUE TITLE
Does Automatonymous support entity framework core integration?

### ISSUE THREAD

**Issue by Alksar** [MassTransit/Automatonymous#57]
Thanks for the great library! 

I see in repository NHibernateIntegration only, but I know, that with MassTransit it is possible to use ef core integration also, so does Automatonymous support entity framework core integration by itself?

**Comment by phatboyg** [comment]
The NHibernate integration is just to map the `State` property to a UserType. Since it supports using an int or string for the property that’s pretty much what you’d use for EF.

**Comment by Alksar** [comment]
Got it, thanks.
