### ISSUE TITLE
Support DI for Activities

### ISSUE THREAD

**Issue by Alksar** [MassTransit/Automatonymous#60]
Masstransit.AutomatonymousIntegration supported dependency injection for Activities with [ContainerFactoryActivity](https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit.AutomatonymousIntegration/Activities/ContainerFactoryActivity.cs) (IStateMachineActivityFactory).

Is it possible to do something similar for pure Automatonymous?

**Comment by phatboyg** [comment]
Doubtful, due to the dependency issues it would create. You're welcome to do it yourself though.

**Comment by dynamatt** [comment]
For anyone looking for this broken link, here is the [ContainerFactoryActivity](https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit/Automatonymous/Activities/ContainerFactoryActivity.cs).
