### ISSUE TITLE
.NET Core support for Automatonymous.Visualizer

### ISSUE THREAD

**Issue by Serenya** [MassTransit/Automatonymous#61]
Hi,

It's a feature request to add support of .NET Core to Automatonymous.Visualizer library. Currently only classic .NET Framework is supported:

![image](https://user-images.githubusercontent.com/4124557/63588022-bba5ed00-c5a5-11e9-80c3-12a72ef1397f.png)

**Comment by Serenya** [comment]
Here I've found compatible .NET Core QuickGraph library https://www.nuget.org/packages/QuickGraph.NETStandard/

**Comment by phatboyg** [comment]
That helps, should be a fairly easy port.
