### ISSUE TITLE
How well is Automatonymous optimized?

### ISSUE THREAD

**Issue by HurricanKai** [MassTransit/Automatonymous#65]
Automatonymous looks really interesting to me, but It seems like I'm forced to do async/await everywhere, and I'm not sure how it's performance is, with that in mind.
I don't really care for Automatonymous doing a lot of IO work, maybe here and there in combination with Mass Transit, but a lot of in-memory usage would be used. Is this a use case Automatonymous was designed for at all?

**Comment by phatboyg** [comment]
Automatonymous, and the libraries it is built around, is highly optimized. In most cases, an async stack frame isn't created and synchronous methods are used.

As this isn't an issue, I'm going to close it.

**Comment by HurricanKai** [comment]
@phatboyg Thanks, but digging around the source I couldn't find, for example, how to raise an event without having to use async

**Comment by phatboyg** [comment]
There is no way to raise an event without using async.
