### ISSUE TITLE
State machine graph

### ISSUE THREAD

**Issue by iulian-olteanu** [MassTransit/Automatonymous#85]
Hello,
Before the upgrade to 8.0.2, this used to work :

```
using Automatonymous.Graphing;

var generator = new StateMachineGraphvizGenerator(this.GetGraph());
_logging.LogInformation("Graph for SAGA is {Graph}", generator.CreateDotFile());
```

How could I get the state machine graph ? 

I am trying to avoid "Argument type 'MassTransit.SagaStateMachine.StateMachineGraph' is not assignable to parameter type 'Automatonymous.Graphing.StateMachineGraph'"

**Comment by phatboyg** [comment]
You need to use the new NuGet package from MassTransit v8. Clearly explained in the [upgrade documentation](https://masstransit-project.com/getting-started/upgrade-v6.html#version-8).

**Comment by iulian-olteanu** [comment]
You are correct. Sorry I missed it. Thank you so much !
